Repository AboutSav/NBread-Frontend-2022, pull requests merged in 2022-03, with the labels that each got.

#2 뷰 라우터 설치 및 기본파일 삭제
  package.json
  src/App.vue
  src/components/HelloWorld.vue
  src/main.js
  src/router/index.js
  src/views/AboutView.vue
  src/views/HomeView.vue
  yarn.lock
Labels: everyone's task

#3 Github push테스트를 위한 AboutView 파일 수정
  package-lock.json
  package.json
  src/views/AboutView.vue
  yarn.lock
Labels: individual task

#6 테스트를 위한 HyeongView 파일 추가
  src/views/HyeongView.vue
  yarn.lock
Labels: individual task

#5 테스트용 JunView 파일 작성
  src/views/JunView.vue
Labels: individual task

#7 Router 파일 수정 및 경로 추가
  src/router/index.js
Labels: everyone's task

#8 테스트를 위한 view 파일 수정
  src/views/HyeongView.vue
Labels: individual task

#9 테스트
  src/views/AboutView.vue
Labels: enhancement
